#Experiment 12
## Name:Kshitij Dalvi
## Prn:25070123066
## Topic:
Preprocessing on dataset and dealing with mising values

In [ ]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'C1':[11,21, np.nan],
                 'C2':[15, np.nan,np.nan],
                 'C3':[10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [ ]:
df1.isna() #Blen Function

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
df1.notna()

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [ ]:
df1.isna().sum()

C1    1
C2    2
C3    0
dtype: int64

In [ ]:
df1.dropna()

     C1    C2  C3
0  11.0  15.0  10

In [ ]:
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [ ]:
df1.fillna(value='DEFAAULT')

         C1        C2  C3
0      11.0      15.0  10
1      21.0  DEFAAULT  20
2  DEFAAULT  DEFAAULT  30

In [ ]:
df1.fillna(df1.mean()) #Mean values of columns are caculated

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [ ]:
# Preprocessing on a Dataset-1
import pandas as pd
import numpy as np
data={
    "Roll No" : [1,2,3,4,5],
    "Name" : ["Asha","Harshit","Khush","Kshitij","Anik"],
    "Age" : [20,"-",21,20,"22"],
    "Marks" :[85,90,"-",88,76],
    "Department":["CSE","IT","CSE","MECH","AIML"],
    "Admission_Date": ["01-06-2023","03-06-2023","05-06-2023","07-06-2023","10-06-2023"]
}
df=pd.DataFrame(data)
print(df)

   Roll No     Name Age Marks Department Admission_Date
0        1     Asha  20    85        CSE     01-06-2023
1        2  Harshit   -    90         IT     03-06-2023
2        3    Khush  21     -        CSE     05-06-2023
3        4  Kshitij  20    88       MECH     07-06-2023
4        5     Anik  22    76       AIML     10-06-2023

In [ ]:
import pandas as pd
import numpy as np
#Step1
df = pd.read_csv('student_data.csv')
print("Original Data")
print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'student_data.csv'

In [ ]:
# Step 2 :Replac'-'with NaN to mark missing values

df.replace("-", np.nan, inplace=True)
#convert columns to numeric where needed
df["Age"]=pd.to_numeric(df["Age"],errors='coerce')
df["Marks"]=pd.to_numeric(df["Marks"],errors='coerce')

'''When converting data (like strings→ datetime),
if some values are invaid or cannot be converted,
instead of throwing an error,it will :
Replace those invalid values with NaT (not a time)'''
df

/tmp/ipykernel_4398/1887357149.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("-", np.nan, inplace=True)

   Roll No     Name   Age  Marks Department Admission_Date
0        1     Asha  20.0   85.0        CSE     01-06-2023
1        2  Harshit   NaN   90.0         IT     03-06-2023
2        3    Khush  21.0    NaN        CSE     05-06-2023
3        4  Kshitij  20.0   88.0       MECH     07-06-2023
4        5     Anik  22.0   76.0       AIML     10-06-2023

In [ ]:
# Step 3 : Check missing values
print ("\nMissing values")
print(df.isnull().sum())

Missing values
Roll No           0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

In [ ]:
# fill missing age with mean
mean_age = df['Age'].mean()
df['Age'].fillna(mean_age, inplace=True)
df

/tmp/ipykernel_4398/1584995129.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(mean_age, inplace=True)

   Roll No     Name    Age  Marks Department Admission_Date
0        1     Asha  20.00   85.0        CSE     01-06-2023
1        2  Harshit  20.75   90.0         IT     03-06-2023
2        3    Khush  21.00    NaN        CSE     05-06-2023
3        4  Kshitij  20.00   88.0       MECH     07-06-2023
4        5     Anik  22.00   76.0       AIML     10-06-2023

In [ ]:
# fill missing marks with median
median_marks = df['Marks'].median()
df['Marks'].fillna(median_marks, inplace=True)
df

/tmp/ipykernel_4398/309866859.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Marks'].fillna(median_marks, inplace=True)

   Roll No     Name    Age  Marks Department Admission_Date
0        1     Asha  20.00   85.0        CSE     01-06-2023
1        2  Harshit  20.75   90.0         IT     03-06-2023
2        3    Khush  21.00   86.5        CSE     05-06-2023
3        4  Kshitij  20.00   88.0       MECH     07-06-2023
4        5     Anik  22.00   76.0       AIML     10-06-2023

In [ ]:
print(df.isnull().sum())

Roll No           0
Name              0
Age               0
Marks             0
Department        0
Admission_Date    0
dtype: int64

In [ ]:
#Step 5 : Fix inconsistent text formatting
df["Department"] = df["Department"].str.upper()
df

   Roll No     Name    Age  Marks Department Admission_Date
0        1     Asha  20.00   85.0        CSE     01-06-2023
1        2  Harshit  20.75   90.0         IT     03-06-2023
2        3    Khush  21.00   86.5        CSE     05-06-2023
3        4  Kshitij  20.00   88.0       MECH     07-06-2023
4        5     Anik  22.00   76.0       AIML     10-06-2023

In [ ]:
#Step 6: Convert Admission_Date tostandard datetime format
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], errors='coerce')
df

   Roll No     Name    Age  Marks Department Admission_Date
0        1     Asha  20.00   85.0        CSE     2023-01-06
1        2  Harshit  20.75   90.0         IT     2023-03-06
2        3    Khush  21.00   86.5        CSE     2023-05-06
3        4  Kshitij  20.00   88.0       MECH     2023-07-06
4        5     Anik  22.00   76.0       AIML     2023-10-06

In [ ]:
#Step 7 : show cleaned data
print("\nCleaned Data")
print(df)

Cleaned Data
   Roll No     Name    Age  Marks Department Admission_Date
0        1     Asha  20.00   85.0        CSE     01-06-2023
1        2  Harshit  20.75   90.0         IT     03-06-2023
2        3    Khush  21.00   86.5        CSE     05-06-2023
3        4  Kshitij  20.00   88.0       MECH     07-06-2023
4        5     Anik  22.00   76.0       AIML     10-06-2023

In [ ]:
# Step 8 : Save cleared dataset
df.to_csv("cleaed_student_data.csv",index=False)

print('\nCleaned CSV fie saved as cleaned_student_data.csv')

Cleaned CSV fie saved as cleaned_student_data.csv

In [ ]:
# Working with mssing values on Dataset - 2
df=pd.read_csv('cleaed_student_data.csv')
df

   Roll No     Name    Age  Marks Department Admission_Date
0        1     Asha  20.00   85.0        CSE     01-06-2023
1        2  Harshit  20.75   90.0         IT     03-06-2023
2        3    Khush  21.00   86.5        CSE     05-06-2023
3        4  Kshitij  20.00   88.0       MECH     07-06-2023
4        5     Anik  22.00   76.0       AIML     10-06-2023

In [ ]:
df.isna().sum() #Attributes are displayed

Roll No           0
Name              0
Age               0
Marks             0
Department        0
Admission_Date    0
dtype: int64

In [ ]:
df = pd.read_csv('Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
#Imputing the Missing Value
#1. Luggage Room
df ['Luggage.room'] = df['Luggage.room'].fillna(value=df['Luggage.room'].mean())

In [ ]:
#2.Rear.seat.room
df ['Rear.seat.room'] = df ['Rear.seat.room'].fillna(value=df['Rear.seat.room'].mean())

In [ ]:
#3.AirBags
df['AirBags'] = df['AirBags'].fillna(value=df['AirBags'].mode().values[0])

In [ ]:
#Save cleaned dataset
df.to_csv("cleaned_Cars93.csv", index=False)