# Experiment 9
## Tools or EDA - Study of Pandas Library
## Name - Kshitij Dalvi
## PRN - 25070123066
## Batch - A3

In [ ]:
# Pandas = Panel Data
'''used for :
Structured data
EDA
Data Cleaning'''

'used for : \nStructured data\nEDA\nData Cleaning'

In [ ]:
import pandas as pd
s = pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
import pandas as pd

# Create a DataFrame
data = {
    "Name":["Kshitij","Khush","Vishvam"],
    "Marks":[85,90,78]
}
df = pd.DataFrame(data)
df

      Name  Marks
0  Kshitij     85
1    Khush     90
2  Vishvam     78

In [ ]:
# Give first five and last five datas
print(df.head())
print(df.tail())

      Name  Marks
0  Kshitij     85
1    Khush     90
2  Vishvam     78
      Name  Marks
0  Kshitij     85
1    Khush     90
2  Vishvam     78

In [ ]:
# Find structure of DataFrame
df.shape

(3, 2)

In [ ]:
# Find dimensions of DataFrame
df.ndim

2

In [ ]:
# Find size of the DataFrame
df.size

6

In [ ]:
# Display Column Names
df.columns

Index(['Name', 'Marks'], dtype='object')

In [ ]:
# Check Data type of Each Column
df.dtypes

Name     object
Marks     int64
dtype: object

In [ ]:
# Access Individual Column
print(df["Name"])
df["Marks"]

0    Kshitij
1      Khush
2    Vishvam
Name: Name, dtype: object

0    85
1    90
2    78
Name: Marks, dtype: int64

In [ ]:
# Access specific row
df.loc[1]

Name     Khush
Marks       90
Name: 1, dtype: object

In [ ]:
# Add a new column
'''If marks 80-90-First class
If marks>=90-Distinction
If Marks <80-Second Class'''
df["Grade"] = ["First Class","Distinction","Second Class"]
df

      Name  Marks         Grade
0  Kshitij     85   First Class
1    Khush     90   Distinction
2  Vishvam     78  Second Class

In [ ]:
# Update the data in the data frame
# Change marks of student A to 88.
df.loc[0,"Marks"]=98
df.loc[0,"Grade"]="Distinction"
df

      Name  Marks         Grade
0  Kshitij     98   Distinction
1    Khush     90   Distinction
2  Vishvam     78  Second Class

In [ ]:
# Delete a Column
df.drop("Grade",axis = 1, inplace = True)
df

      Name  Marks
0  Kshitij     98
1    Khush     90
2  Vishvam     78

In [ ]:
# Perform Basic Statistical Analysis
mean1=df["Marks"].mean()
mean1

np.float64(88.66666666666667)

In [ ]:
# Mode (Not applicable when you have integer value)
mode1=df["Marks"].mode()
print(mode1)

0    78
1    90
2    98
Name: Marks, dtype: int64

In [ ]:
#Find minimum and maximum value of given data set
min1=df["Marks"].min()
print(min1)
max1=df["Marks"].max()
print(max1)

78
98

In [ ]:
# Apply condition (Filtering)
# Display students scoring more than 80
df[df["Marks"]>80]

      Name  Marks
0  Kshitij     98
1    Khush     90

In [ ]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'C1':[11,21,np.nan],'C2':[15,np.nan,np.nan],'C3':[10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [ ]:
# Check if non integer number
df1.isna() #Boolean function

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
# Check if integer number
df1.notna() #Boolean

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [ ]:
df1.isna().sum() # Checks column-wise

C1    1
C2    2
C3    0
dtype: int64

In [ ]:
# NaN rows drop
df1.dropna()

     C1    C2  C3
0  11.0  15.0  10