# Experiment 14
# Data Normalization and Data Type Conversion
## Name - Kshitij Dalvi
## Batch - A3
## PRN - 25070123066

### Data Normalization

In [ ]:
# Data set
import pandas as pd
import numpy as np
data = {
    'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price':[55000,20000,30000,2000,8000,45000],
    'Units_Sold':[25,60,35,80,50,15],
    'Discount':[10,15,12,20,18,8]
}
df = pd.DataFrame(data)
df

      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

In [ ]:
# Min-Max Normalization
# Min-Max Normalization for Price
df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min()) #Learn formula
df

      Product  Price  Units_Sold  Discount  Price_MinMax
0      Laptop  55000          25        10      1.000000
1      Mobile  20000          60        15      0.339623
2      Tablet  30000          35        12      0.528302
3  Headphones   2000          80        20      0.000000
4  Smartwatch   8000          50        18      0.113208
5      Camera  45000          15         8      0.811321

In [ ]:
df['Units_Sold_MinMax'] = (df['Units_Sold'] - df['Units_Sold'].min()) / (df['Units_Sold'].max() - df['Units_Sold'].min())
df

      Product  Price  Units_Sold  Discount  Price_MinMax  Units_Sold_MinMax
0      Laptop  55000          25        10      1.000000           0.153846
1      Mobile  20000          60        15      0.339623           0.692308
2      Tablet  30000          35        12      0.528302           0.307692
3  Headphones   2000          80        20      0.000000           1.000000
4  Smartwatch   8000          50        18      0.113208           0.538462
5      Camera  45000          15         8      0.811321           0.000000

In [ ]:
#Normalize multiple columns
cols = ['Price','Units_Sold','Discount']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
df_norm

      Price  Units_Sold  Discount
0  1.000000    0.153846  0.166667
1  0.339623    0.692308  0.583333
2  0.528302    0.307692  0.333333
3  0.000000    1.000000  1.000000
4  0.113208    0.538462  0.833333
5  0.811321    0.000000  0.000000

In [ ]:
# Z-Score Normalization (Standardization)
df['Price_ZScore'] = (df['Price'] - df['Price'].mean()) / df['Price'].std()
df

,Product,Price,Units_Sold,Discount,Price_MinMax,Units_Sold_MinMax,Price_ZScore
0,Laptop,55000,25,10,1.000000,0.153846,1.365931
1,Mobile,20000,60,15,0.339623,0.692308,-0.321396
2,Tablet,30000,35,12,0.528302,0.307692,0.160698
3,Headphones,2000,80,20,0.000000,1.000000,-1.189164
4,Smartwatch,8000,50,18,0.113208,0.538462,-0.899908
5,Camera,45000,15,8,0.811321,0.000000,0.883838

In [ ]:
# Decimal Scaling
df['Price_Decimal'] = df['Price'] / 100000
df

,Product,Price,Units_Sold,Discount,Price_MinMax,Units_Sold_MinMax,Price_ZScore,Price_Decimal
0,Laptop,55000,25,10,1.000000,0.153846,1.365931,0.55
1,Mobile,20000,60,15,0.339623,0.692308,-0.321396,0.20
2,Tablet,30000,35,12,0.528302,0.307692,0.160698,0.30
3,Headphones,2000,80,20,0.000000,1.000000,-1.189164,0.02
4,Smartwatch,8000,50,18,0.113208,0.538462,-0.899908,0.08
5,Camera,45000,15,8,0.811321,0.000000,0.883838,0.45

### Standardization

In [ ]:
data1 = {
    'Order_ID':[101,102,103,104,105,106],
    'Customer_Gender':['Male','Female','Female','Male','Female','Male'],
    'Payment_Method':['UPI','Credit Card','Debit Card','COD','UPI','Debit Card'],
    'City':['Pune','Delhi','Mumbai','Chennai','Surat','Chandigarh'],
    'Product_Category':['Electroncs','Clothing','Home','Electronics','Beauty','Home'],
    'Order_Value':[4500,2300,3200,5200,1800,4100]
}
df = pd.DataFrame(data1)
df

,Order_ID,Customer_Gender,Payment_Method,City,Product_Category,Order_Value
0,101,Male,UPI,Pune,Electroncs,4500
1,102,Female,Credit Card,Delhi,Clothing,2300
2,103,Female,Debit Card,Mumbai,Home,3200
3,104,Male,COD,Chennai,Electronics,5200
4,105,Female,UPI,Surat,Beauty,1800
5,106,Male,Debit Card,Chandigarh,Home,4100

In [ ]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender_Label'] = le.fit_transform(df['Customer_Gender'])
df

,Order_ID,Customer_Gender,Payment_Method,City,Product_Category,Order_Value,Gender_Label
0,101,Male,UPI,Pune,Electroncs,4500,1
1,102,Female,Credit Card,Delhi,Clothing,2300,0
2,103,Female,Debit Card,Mumbai,Home,3200,0
3,104,Male,COD,Chennai,Electronics,5200,1
4,105,Female,UPI,Surat,Beauty,1800,0
5,106,Male,Debit Card,Chandigarh,Home,4100,1

In [ ]:
# One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=['Payment_Method'])
df_encoded

,Order_ID,Customer_Gender,City,Product_Category,Order_Value,Gender_Label,Payment_Method_COD,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,Male,Pune,Electroncs,4500,1,False,False,False,True
1,102,Female,Delhi,Clothing,2300,0,False,True,False,False
2,103,Female,Mumbai,Home,3200,0,False,False,True,False
3,104,Male,Chennai,Electronics,5200,1,True,False,False,False
4,105,Female,Surat,Beauty,1800,0,False,False,False,True
5,106,Male,Chandigarh,Home,4100,1,False,False,True,False

In [ ]:
# Dummy Encoding
df_dummy = pd.get_dummies(df, columns=['Payment_Method'], drop_first=True)
df_dummy

,Order_ID,Customer_Gender,City,Product_Category,Order_Value,Gender_Label,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,Male,Pune,Electroncs,4500,1,False,False,True
1,102,Female,Delhi,Clothing,2300,0,True,False,False
2,103,Female,Mumbai,Home,3200,0,False,True,False
3,104,Male,Chennai,Electronics,5200,1,False,False,False
4,105,Female,Surat,Beauty,1800,0,False,False,True
5,106,Male,Chandigarh,Home,4100,1,False,True,False

# New

In [ ]:
df = pd.read_csv('/content/amazon_products_dataset_Expt-14.csv')

In [ ]:
# MinMax Normalization
'''df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max())
df['Units_Sold_MinMax'] = (df['Units_Sold'] - df['Units_Sold'].min())/(df['Units_Sold'].max())'''
cols = ['Price','Units_Sold','Reviews']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
df_norm

       Price  Units_Sold   Reviews
0   0.020243    0.518519  0.291005
1   0.048583    0.277778  0.148148
2   0.016194    0.203704  0.119048
3   0.089069    0.629630  0.444444
4   0.149798    0.833333  0.695767
5   0.036437    0.592593  0.351852
6   0.024291    0.129630  0.052910
7   0.064777    0.351852  0.185185
8   0.210526    0.481481  0.378307
9   0.028340    0.222222  0.089947
10  0.311741    1.000000  1.000000
11  0.174089    0.407407  0.444444
12  0.052632    0.500000  0.232804
13  0.016194    0.092593  0.031746
14  0.024291    0.240741  0.119048
15  0.251012    0.444444  0.497354
16  0.036437    0.259259  0.089947
17  0.068826    0.648148  0.312169
18  0.109312    0.851852  0.814815
19  0.040486    0.351852  0.148148
20  0.008097    0.148148  0.000000
21  0.089069    0.444444  0.272487
22  0.352227    0.185185  0.219577
23  0.020243    0.259259  0.079365
24  0.129555    0.592593  0.444444
25  0.174089    0.166667  0.148148
26  0.514170    0.129630  0.708995
27  0.076923    0.370370  0.232804
28  0.016194    0.314815  0.121693
29  0.048583    0.351852  0.150794
30  0.392713    0.240741  0.444444
31  0.230769    0.203704  0.351852
32  0.129555    0.666667  0.550265
33  0.473684    0.092593  0.272487
34  0.635628    0.037037  0.444444
35  0.012146    0.166667  0.007937
36  0.020243    0.462963  0.126984
37  0.000000    0.574074  0.047619
38  0.028340    0.259259  0.079365
39  0.048583    0.111111  0.026455
40  0.109312    0.148148  0.113757
41  0.433198    0.074074  0.206349
42  0.190283    0.351852  0.444444
43  1.000000    0.000000  0.365079
44  0.068826    0.444444  0.259259
45  0.311741    0.240741  0.470899
46  0.757085    0.092593  0.325397
47  0.089069    0.185185  0.148148
48  0.129555    0.148148  0.119048
49  0.028340    0.314815  0.089947

In [ ]:
# Zscore
df['Price_ZScore'] = (df['Price'] - df['Price'].mean()) / df['Price'].std()
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_ZScore
0,P101,Wireless Mouse,799,4.3,1520,350,-0.692019
1,P102,Bluetooth Speaker,1499,4.5,980,220,-0.557310
2,P103,USB Keyboard,699,4.1,870,180,-0.711263
3,P104,Gaming Headset,2499,4.6,2100,410,-0.364869
4,P105,Smartwatch,3999,4.4,3050,520,-0.076207
5,P106,Power Bank,1199,4.2,1750,390,-0.615043
6,P107,Laptop Stand,899,4.0,620,140,-0.672775
7,P108,Webcam,1899,4.3,1120,260,-0.480334
8,P109,Portable SSD,5499,4.7,1850,330,0.212455
9,P110,Wireless Charger,999,4.2,760,190,-0.653531
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,0.693559
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.039258
12,P113,Gaming Mouse,1599,4.4,1300,340,-0.538066
13,P114,Tablet Stand,699,4.1,540,120,-0.711263
14,P115,USB Hub,899,4.2,870,200,-0.672775
15,P116,External Hard Drive,6499,4.6,2300,310,0.404897
16,P117,Smartphone Tripod,1199,4.3,760,210,-0.615043
17,P118,Laptop Backpack,1999,4.4,1600,420,-0.461090
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,-0.268648
19,P120,LED Desk Lamp,1299,4.3,980,260,-0.595799
20,P121,Phone Holder,499,4.0,420,150,-0.749752
21,P122,Wireless Keyboard,2499,4.4,1450,310,-0.364869
22,P123,Portable Monitor,8999,4.6,1250,170,0.886000
23,P124,Smart Plug,799,4.2,720,210,-0.692019
24,P125,WiFi Router,3499,4.5,2100,390,-0.172428
25,P126,Graphics Tablet,4599,4.4,980,160,0.039258
26,P127,VR Headset,12999,4.7,3100,140,1.655766
27,P128,Microphone,2199,4.3,1300,270,-0.422601
28,P129,Smart Light Bulb,699,4.2,880,240,-0.711263
29,P130,Laptop Cooling Pad,1499,4.3,990,260,-0.557310
30,P131,Action Camera,9999,4.6,2100,200,1.078442
31,P132,Smart Doorbell,5999,4.5,1750,180,0.308676
32,P133,Streaming Stick,3499,4.4,2500,430,-0.172428
33,P134,Portable Projector,11999,4.6,1450,120,1.463325
34,P135,Gaming Chair,15999,4.7,2100,90,2.233090
35,P136,Desk Organizer,599,4.1,450,160,-0.730508
36,P137,USB Flash Drive,799,4.2,900,320,-0.692019
37,P138,Phone Screen Protector,299,4.0,600,380,-0.788240
38,P139,Laptop Sleeve,999,4.3,720,210,-0.653531
39,P140,Wireless Presenter,1499,4.4,520,130,-0.557310
40,P141,Tablet Keyboard Case,2999,4.5,850,150,-0.268648
41,P142,Smart Thermostat,10999,4.6,1200,110,1.270883
42,P143,Security Camera,4999,4.4,2100,260,0.116235
43,P144,Drone Camera,24999,4.7,1800,70,3.965063
44,P145,Electric Kettle,1999,4.3,1400,310,-0.461090
45,P146,Air Fryer,7999,4.6,2200,200,0.693559
46,P147,Robot Vacuum,18999,4.5,1650,120,2.810415
47,P148,Smart Scale,2499,4.4,980,170,-0.364869
48,P149,Digital Photo Frame,3499,4.3,870,150,-0.172428
49,P150,Portable Fan,999,4.2,760,240,-0.653531

In [ ]:
# Decimal Scaling
df['Price_Decimal'] = df['Price'] / 10000
df['Reviews_Decimal'] = df['Reviews']/10000
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_ZScore,Price_Decimal,Reviews_Decimal
0,P101,Wireless Mouse,799,4.3,1520,350,-0.692019,0.0799,0.152
1,P102,Bluetooth Speaker,1499,4.5,980,220,-0.557310,0.1499,0.098
2,P103,USB Keyboard,699,4.1,870,180,-0.711263,0.0699,0.087
3,P104,Gaming Headset,2499,4.6,2100,410,-0.364869,0.2499,0.210
4,P105,Smartwatch,3999,4.4,3050,520,-0.076207,0.3999,0.305
5,P106,Power Bank,1199,4.2,1750,390,-0.615043,0.1199,0.175
6,P107,Laptop Stand,899,4.0,620,140,-0.672775,0.0899,0.062
7,P108,Webcam,1899,4.3,1120,260,-0.480334,0.1899,0.112
8,P109,Portable SSD,5499,4.7,1850,330,0.212455,0.5499,0.185
9,P110,Wireless Charger,999,4.2,760,190,-0.653531,0.0999,0.076
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,0.693559,0.7999,0.420
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.039258,0.4599,0.210
12,P113,Gaming Mouse,1599,4.4,1300,340,-0.538066,0.1599,0.130
13,P114,Tablet Stand,699,4.1,540,120,-0.711263,0.0699,0.054
14,P115,USB Hub,899,4.2,870,200,-0.672775,0.0899,0.087
15,P116,External Hard Drive,6499,4.6,2300,310,0.404897,0.6499,0.230
16,P117,Smartphone Tripod,1199,4.3,760,210,-0.615043,0.1199,0.076
17,P118,Laptop Backpack,1999,4.4,1600,420,-0.461090,0.1999,0.160
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,-0.268648,0.2999,0.350
19,P120,LED Desk Lamp,1299,4.3,980,260,-0.595799,0.1299,0.098
20,P121,Phone Holder,499,4.0,420,150,-0.749752,0.0499,0.042
21,P122,Wireless Keyboard,2499,4.4,1450,310,-0.364869,0.2499,0.145
22,P123,Portable Monitor,8999,4.6,1250,170,0.886000,0.8999,0.125
23,P124,Smart Plug,799,4.2,720,210,-0.692019,0.0799,0.072
24,P125,WiFi Router,3499,4.5,2100,390,-0.172428,0.3499,0.210
25,P126,Graphics Tablet,4599,4.4,980,160,0.039258,0.4599,0.098
26,P127,VR Headset,12999,4.7,3100,140,1.655766,1.2999,0.310
27,P128,Microphone,2199,4.3,1300,270,-0.422601,0.2199,0.130
28,P129,Smart Light Bulb,699,4.2,880,240,-0.711263,0.0699,0.088
29,P130,Laptop Cooling Pad,1499,4.3,990,260,-0.557310,0.1499,0.099
30,P131,Action Camera,9999,4.6,2100,200,1.078442,0.9999,0.210
31,P132,Smart Doorbell,5999,4.5,1750,180,0.308676,0.5999,0.175
32,P133,Streaming Stick,3499,4.4,2500,430,-0.172428,0.3499,0.250
33,P134,Portable Projector,11999,4.6,1450,120,1.463325,1.1999,0.145
34,P135,Gaming Chair,15999,4.7,2100,90,2.233090,1.5999,0.210
35,P136,Desk Organizer,599,4.1,450,160,-0.730508,0.0599,0.045
36,P137,USB Flash Drive,799,4.2,900,320,-0.692019,0.0799,0.090
37,P138,Phone Screen Protector,299,4.0,600,380,-0.788240,0.0299,0.060
38,P139,Laptop Sleeve,999,4.3,720,210,-0.653531,0.0999,0.072
39,P140,Wireless Presenter,1499,4.4,520,130,-0.557310,0.1499,0.052
40,P141,Tablet Keyboard Case,2999,4.5,850,150,-0.268648,0.2999,0.085
41,P142,Smart Thermostat,10999,4.6,1200,110,1.270883,1.0999,0.120
42,P143,Security Camera,4999,4.4,2100,260,0.116235,0.4999,0.210
43,P144,Drone Camera,24999,4.7,1800,70,3.965063,2.4999,0.180
44,P145,Electric Kettle,1999,4.3,1400,310,-0.461090,0.1999,0.140
45,P146,Air Fryer,7999,4.6,2200,200,0.693559,0.7999,0.220
46,P147,Robot Vacuum,18999,4.5,1650,120,2.810415,1.8999,0.165
47,P148,Smart Scale,2499,4.4,980,170,-0.364869,0.2499,0.098
48,P149,Digital Photo Frame,3499,4.3,870,150,-0.172428,0.3499,0.087
49,P150,Portable Fan,999,4.2,760,240,-0.653531,0.0999,0.076

In [ ]:
# Turning Categorical variables into quantitative variables
df = pd.read_csv('/content/Student-Dataset.csv')
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [ ]:
# Label encoding-placement stats
df['Placement_Label'] = le.fit_transform(df['Placement_Status'])
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Placement_Label
0,101,Female,Computer,8.2,0,92,Placed,450000,1
1,102,Male,IT,7.5,1,85,Not Placed,0,0
2,103,Female,ENTC,9.1,0,96,Placed,550000,1
3,104,Male,Mechanical,6.8,2,78,Not Placed,0,0
4,105,Female,Computer,8.7,0,88,Placed,480000,1
5,106,Male,Civil,7.2,3,72,Not Placed,0,0
6,107,Female,IT,8.9,0,91,Placed,500000,1
7,108,Male,Computer,6.5,1,80,Not Placed,0,0
8,109,Female,ENTC,7.8,0,84,Placed,420000,1
9,110,Male,Mechanical,7.0,2,76,Not Placed,0,0

In [ ]:
# One-Hot Encoding - Department
df_encoded = pd.get_dummies(df, columns=['Department'])
df_encoded

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Placement_Label,Department_Civil,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,Placed,450000,1,False,True,False,False,False
1,102,Male,7.5,1,85,Not Placed,0,0,False,False,False,True,False
2,103,Female,9.1,0,96,Placed,550000,1,False,False,True,False,False
3,104,Male,6.8,2,78,Not Placed,0,0,False,False,False,False,True
4,105,Female,8.7,0,88,Placed,480000,1,False,True,False,False,False
5,106,Male,7.2,3,72,Not Placed,0,0,True,False,False,False,False
6,107,Female,8.9,0,91,Placed,500000,1,False,False,False,True,False
7,108,Male,6.5,1,80,Not Placed,0,0,False,True,False,False,False
8,109,Female,7.8,0,84,Placed,420000,1,False,False,True,False,False
9,110,Male,7.0,2,76,Not Placed,0,0,False,False,False,False,True

In [ ]:
# Dummy encoding - Department
df_dummy = pd.get_dummies(df, columns=['Department'], drop_first=True)
df_dummy

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Placement_Label,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,Placed,450000,1,True,False,False,False
1,102,Male,7.5,1,85,Not Placed,0,0,False,False,True,False
2,103,Female,9.1,0,96,Placed,550000,1,False,True,False,False
3,104,Male,6.8,2,78,Not Placed,0,0,False,False,False,True
4,105,Female,8.7,0,88,Placed,480000,1,True,False,False,False
5,106,Male,7.2,3,72,Not Placed,0,0,False,False,False,False
6,107,Female,8.9,0,91,Placed,500000,1,False,False,True,False
7,108,Male,6.5,1,80,Not Placed,0,0,True,False,False,False
8,109,Female,7.8,0,84,Placed,420000,1,False,True,False,False
9,110,Male,7.0,2,76,Not Placed,0,0,False,False,False,True