# Experiment 10

## Create Dataset and Load Dataset
## Name: Kshitij Dalvi
## PRN : 25070123066
## Class: ENTC- A3
## Date : 20th February 2026

In [ ]:
import pandas as pd

data ={
    "Roll_No": [101,102,103,104,105] ,
    "Gender":["Female","Male","Female","Male","Female"],
    "Department":["Computer","IT","ENTC","Mechanical","Computer"],
    "CGPA": [8.2,7.5,9.1,6.8,8.7]
    }

df=pd.DataFrame(data)

df.to_csv("student.csv", index=False)
df

   Roll_No  Gender  Department  CGPA
0      101  Female    Computer   8.2
1      102    Male          IT   7.5
2      103  Female        ENTC   9.1
3      104    Male  Mechanical   6.8
4      105  Female    Computer   8.7

In [ ]:
# Access information of column department

df["Department"]

0      Computer
1            IT
2          ENTC
3    Mechanical
4      Computer
Name: Department, dtype: object

In [ ]:
# Access infromation of PRN 103

df[df["Roll_No"] == 103]

   Roll_No  Gender Department  CGPA
2      103  Female       ENTC   9.1

In [ ]:
# Find out data type of each column

df.dtypes

Roll_No         int64
Gender         object
Department     object
CGPA          float64
dtype: object

In [ ]:
# Perform mean, median and mode operation

print("Mean =",df.mean(numeric_only=True))
print("Median =",df.median(numeric_only=True))
print("Mode =",df.mode( numeric_only=True))

Mean = Roll_No    103.00
CGPA         8.06
dtype: float64
Median = Roll_No    103.0
CGPA         8.2
dtype: float64
Mode =    Roll_No  CGPA
0      101   6.8
1      102   7.5
2      103   8.2
3      104   8.7
4      105   9.1

In [ ]:
# Insert a new column Grade

df["Grade"] = ["A","B","A","C","A"]
df

   Roll_No  Gender  Department  CGPA Grade
0      101  Female    Computer   8.2     A
1      102    Male          IT   7.5     B
2      103  Female        ENTC   9.1     A
3      104    Male  Mechanical   6.8     C
4      105  Female    Computer   8.7     A

In [ ]:
# Insert a new column Grade

df["Grade"] = ["A","B","A","C","A"]
df

   Roll_No  Department  CGPA Grade
0      101    Computer   8.2     A
1      102          IT   7.5     B
2      103        ENTC   9.1     A
3      104  Mechanical   6.8     C
4      105    Computer   8.7     A

In [ ]:
# Delete Gender column

df.drop("Gender",axis = 1, inplace = True)
df

   Roll_No  Department  CGPA Grade
0      101    Computer   8.2     A
1      102          IT   7.5     B
2      103        ENTC   9.1     A
3      104  Mechanical   6.8     C
4      105    Computer   8.7     A

In [ ]:
# CGPA of topper
max1=df["CGPA"].max()
print(max1)

9.1

In [ ]:
# CGPA of PRN 105
df[df["Roll_No"] == 105]["CGPA"]

4    8.7
Name: CGPA, dtype: float64

In [ ]:
# upload the dataset
import pandas as pd
import numpy as np

df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.size

930

In [ ]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [ ]:
df.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [ ]:
df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000
mean,19.509677,22.365591,143.827957,5.086022,27.829670,13.890244
std,9.659430,5.619812,52.374410,1.038979,2.989072,2.997967
min,7.400000,15.000000,55.000000,2.000000,19.000000,6.000000
25%,12.200000,18.000000,103.000000,4.000000,26.000000,12.000000
50%,17.700000,21.000000,140.000000,5.000000,27.500000,14.000000
75%,23.300000,25.000000,170.000000,6.000000,30.000000,15.000000
max,61.900000,46.000000,300.000000,8.000000,36.000000,22.000000